# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/shubhang/eldlabs/lab5/lab5.cache/wt [current_project]
set_property parent.project_path /home/shubhang/eldlabs/lab5/lab5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /home/shubhang/ELD/blockram.coe
read_ip /home/shubhang/eldlabs/lab5/lab5.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/shubhang/eldlabs/lab5/lab5.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp]
set_property used_in_implementation false [get_files -all /home/shubhang/eldlabs/lab5/lab5.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files /home/shubhang/eldlabs/lab5/lab5.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci]

read_verilog -library xil_defaultlib {
  /home/shubhang/eldlabs/lab5/lab5.srcs/sources_1/imports/new/seven_seg_display.v
  /home/shubhang/eldlabs/lab5/lab5.srcs/sources_1/new/frequency_divider.v
  /home/shubhang/eldlabs/lab5/lab5.srcs/sources_1/new/binarytobcd.v
  /home/shubhang/eldlabs/lab5/lab5.srcs/sources_1/new/top.v
}
read_xdc /home/shubhang/eldlabs/lab5/lab5.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files /home/shubhang/eldlabs/lab5/lab5.srcs/constrs_1/new/cons.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top top -part xc7a35tcpg236-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
