set_property PACKAGE_PIN F22 [get_ports {a1}]
set_property IOSTANDARD LVCMOS33 [get_ports {a1}]
set_property PACKAGE_PIN G22 [get_ports {a2}]
set_property IOSTANDARD LVCMOS33 [get_ports {a2}]
set_property PACKAGE_PIN H22 [get_ports {a3}]
set_property IOSTANDARD LVCMOS33 [get_ports {a3}]
set_property PACKAGE_PIN F21 [get_ports {score1}]
set_property IOSTANDARD LVCMOS33 [get_ports {score1}]

set_property PACKAGE_PIN H19 [get_ports {b1}]
set_property IOSTANDARD LVCMOS33 [get_ports {b1}]
set_property PACKAGE_PIN H18 [get_ports {b2}]
set_property IOSTANDARD LVCMOS33 [get_ports {b2}]
set_property PACKAGE_PIN H17 [get_ports {b3}]
set_property IOSTANDARD LVCMOS33 [get_ports {b3}]
set_property PACKAGE_PIN M15 [get_ports {score2}]
set_property IOSTANDARD LVCMOS33 [get_ports {score2}]

set_property PACKAGE_PIN T22 [get_ports {aout}]
set_property IOSTANDARD LVCMOS33 [get_ports {aout}]
set_property PACKAGE_PIN U14 [get_ports {bout}]
set_property IOSTANDARD LVCMOS33 [get_ports {bout}]