# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/shubhang/ELD/fulladder/fulladder.cache/wt [current_project]
set_property parent.project_path /home/shubhang/ELD/fulladder/fulladder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/shubhang/ELD/fulladder/fulladder.srcs/sources_1/new/halfadder.v
  /home/shubhang/ELD/fulladder/fulladder.srcs/sources_1/new/fulladder.v
  /home/shubhang/ELD/fulladder/fulladder.srcs/sources_1/new/fourbitoperator.v
}
read_xdc /home/shubhang/ELD/fulladder/fulladder.srcs/constrs_1/new/fourbitoperatorcons.xdc
set_property used_in_implementation false [get_files /home/shubhang/ELD/fulladder/fulladder.srcs/constrs_1/new/fourbitoperatorcons.xdc]

synth_design -top fourbitoperator -part xc7z020clg484-1
write_checkpoint -noxdef fourbitoperator.dcp
catch { report_utilization -file fourbitoperator_utilization_synth.rpt -pb fourbitoperator_utilization_synth.pb }
