# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/shubhang/eldlabs/PMOD_Keypad/PMOD_Keypad.cache/wt [current_project]
set_property parent.project_path /home/shubhang/eldlabs/PMOD_Keypad/PMOD_Keypad.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/shubhang/eldlabs/PMOD_Keypad/PMOD_Keypad.srcs/sources_1/new/sseg.v
  /home/shubhang/eldlabs/PMOD_Keypad/PMOD_Keypad.srcs/sources_1/new/decoder.v
  /home/shubhang/eldlabs/PMOD_Keypad/PMOD_Keypad.srcs/sources_1/new/top.v
}
read_xdc /home/shubhang/eldlabs/PMOD_Keypad/PMOD_Keypad.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /home/shubhang/eldlabs/PMOD_Keypad/PMOD_Keypad.srcs/constrs_1/new/constraints.xdc]

synth_design -top top -part xc7a35tcpg236-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
