set_property PACKAGE_PIN W19 [get_ports {push_button_a}]
set_property IOSTANDARD LVCMOS33 [get_ports {push_button_a}]

set_property PACKAGE_PIN T17 [get_ports {push_button_b}]
set_property IOSTANDARD LVCMOS33 [get_ports {push_button_b}]

set_property PACKAGE_PIN W5 [get_ports {clock}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock}]

set_property PACKAGE_PIN U18 [get_ports {clear}]
set_property IOSTANDARD LVCMOS33 [get_ports {clear}]

set_property PACKAGE_PIN N3 [get_ports {ledoutput}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledoutput}]


set_property PACKAGE_PIN W18 [get_ports {e}]
set_property IOSTANDARD LVCMOS33 [get_ports {e}]
set_property PACKAGE_PIN V19 [get_ports {d}]
set_property IOSTANDARD LVCMOS33 [get_ports {d}]
set_property PACKAGE_PIN U19 [get_ports {c}]
set_property IOSTANDARD LVCMOS33 [get_ports {c}]
set_property PACKAGE_PIN E19 [get_ports {b}]
set_property IOSTANDARD LVCMOS33 [get_ports {b}]
set_property PACKAGE_PIN U16 [get_ports {a}]
set_property IOSTANDARD LVCMOS33 [get_ports {a}]


set_property PACKAGE_PIN W4 [get_ports {boardanode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardanode[3]}]
set_property PACKAGE_PIN V4 [get_ports {boardanode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardanode[2]}]
set_property PACKAGE_PIN U4 [get_ports {boardanode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardanode[1]}]
set_property PACKAGE_PIN U2 [get_ports {boardanode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardanode[0]}]

set_property PACKAGE_PIN W7 [get_ports {boardcathode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardcathode[7]}]
set_property PACKAGE_PIN W6 [get_ports {boardcathode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardcathode[6]}]
set_property PACKAGE_PIN U8 [get_ports {boardcathode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardcathode[5]}]
set_property PACKAGE_PIN V8 [get_ports {boardcathode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardcathode[4]}]
set_property PACKAGE_PIN U5 [get_ports {boardcathode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardcathode[3]}]
set_property PACKAGE_PIN V5 [get_ports {boardcathode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardcathode[2]}]
set_property PACKAGE_PIN U7 [get_ports {boardcathode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardcathode[1]}]
set_property PACKAGE_PIN V7 [get_ports {boardcathode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardcathode[0]}]
