set_property PACKAGE_PIN W5 [get_ports {clock}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock}]

set_property PACKAGE_PIN H1 [get_ports {rows[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rows[0]}]
set_property PACKAGE_PIN K2 [get_ports {rows[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rows[1]}]
set_property PACKAGE_PIN H2 [get_ports {rows[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rows[2]}]
set_property PACKAGE_PIN G3 [get_ports {rows[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rows[3]}]

set_property PACKAGE_PIN J1 [get_ports {columns[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {columns[0]}]
set_property PACKAGE_PIN L2 [get_ports {columns[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {columns[1]}]
set_property PACKAGE_PIN J2 [get_ports {columns[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {columns[2]}]
set_property PACKAGE_PIN G2 [get_ports {columns[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {columns[3]}]

set_property PACKAGE_PIN U18 [get_ports {clear}]
set_property IOSTANDARD LVCMOS33 [get_ports {clear}]

set_property PACKAGE_PIN W19 [get_ports {pulseinput}]
set_property IOSTANDARD LVCMOS33 [get_ports {pulseinput}]

set_property PACKAGE_PIN A14 [get_ports {sseg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[6]}]
set_property PACKAGE_PIN A16 [get_ports {sseg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[5]}]
set_property PACKAGE_PIN B15 [get_ports {sseg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[4]}]
set_property PACKAGE_PIN B16 [get_ports {sseg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[3]}]
set_property PACKAGE_PIN K17 [get_ports {sseg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[2]}]
set_property PACKAGE_PIN M18 [get_ports {sseg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[1]}]
set_property PACKAGE_PIN N17 [get_ports {sseg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[0]}]

set_property PACKAGE_PIN P18 [get_ports {anode}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode}]