# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/PWM_block_design/PWM_block_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_block_design || ORIG_REF_NAME==PWM_block_design}]

# IP: bd/PWM_block_design/ip/PWM_block_design_ip_0_0/PWM_block_design_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_block_design_ip_0_0 || ORIG_REF_NAME==PWM_block_design_ip_0_0}]

# IP: bd/PWM_block_design/ip/PWM_block_design_processing_system7_0_0/PWM_block_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_block_design_processing_system7_0_0 || ORIG_REF_NAME==PWM_block_design_processing_system7_0_0}]

# IP: bd/PWM_block_design/ip/PWM_block_design_processing_system7_0_axi_periph_0/PWM_block_design_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_block_design_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==PWM_block_design_processing_system7_0_axi_periph_0}]

# IP: bd/PWM_block_design/ip/PWM_block_design_rst_processing_system7_0_100M_0/PWM_block_design_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_block_design_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==PWM_block_design_rst_processing_system7_0_100M_0}]

# IP: bd/PWM_block_design/ip/PWM_block_design_auto_pc_0/PWM_block_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_block_design_auto_pc_0 || ORIG_REF_NAME==PWM_block_design_auto_pc_0}]

# XDC: bd/PWM_block_design/ip/PWM_block_design_processing_system7_0_0/PWM_block_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PWM_block_design_processing_system7_0_0 || ORIG_REF_NAME==PWM_block_design_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/PWM_block_design/ip/PWM_block_design_rst_processing_system7_0_100M_0/PWM_block_design_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_block_design_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==PWM_block_design_rst_processing_system7_0_100M_0}]

# XDC: bd/PWM_block_design/ip/PWM_block_design_rst_processing_system7_0_100M_0/PWM_block_design_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PWM_block_design_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==PWM_block_design_rst_processing_system7_0_100M_0}]

# XDC: bd/PWM_block_design/ip/PWM_block_design_rst_processing_system7_0_100M_0/PWM_block_design_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/PWM_block_design/ip/PWM_block_design_auto_pc_0/PWM_block_design_auto_pc_0_ooc.xdc

# XDC: bd/PWM_block_design/PWM_block_design_ooc.xdc
