# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/shubhang/eldlabs/lab10/lab10.cache/wt [current_project]
set_property parent.project_path /home/shubhang/eldlabs/lab10/lab10.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /home/shubhang/eldlabs/ip_repo/ip_1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /home/shubhang/eldlabs/lab10/lab10.srcs/sources_1/bd/PWM_block_design/PWM_block_design.bd
set_property used_in_implementation false [get_files -all /home/shubhang/eldlabs/lab10/lab10.srcs/sources_1/bd/PWM_block_design/ip/PWM_block_design_processing_system7_0_0/PWM_block_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/shubhang/eldlabs/lab10/lab10.srcs/sources_1/bd/PWM_block_design/ip/PWM_block_design_rst_processing_system7_0_100M_0/PWM_block_design_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/shubhang/eldlabs/lab10/lab10.srcs/sources_1/bd/PWM_block_design/ip/PWM_block_design_rst_processing_system7_0_100M_0/PWM_block_design_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/shubhang/eldlabs/lab10/lab10.srcs/sources_1/bd/PWM_block_design/ip/PWM_block_design_rst_processing_system7_0_100M_0/PWM_block_design_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shubhang/eldlabs/lab10/lab10.srcs/sources_1/bd/PWM_block_design/ip/PWM_block_design_auto_pc_0/PWM_block_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/shubhang/eldlabs/lab10/lab10.srcs/sources_1/bd/PWM_block_design/PWM_block_design_ooc.xdc]
set_property is_locked true [get_files /home/shubhang/eldlabs/lab10/lab10.srcs/sources_1/bd/PWM_block_design/PWM_block_design.bd]

read_verilog -library xil_defaultlib /home/shubhang/eldlabs/lab10/lab10.srcs/sources_1/bd/PWM_block_design/hdl/PWM_block_design_wrapper.v
read_xdc /home/shubhang/eldlabs/lab10/lab10.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /home/shubhang/eldlabs/lab10/lab10.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top PWM_block_design_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef PWM_block_design_wrapper.dcp
catch { report_utilization -file PWM_block_design_wrapper_utilization_synth.rpt -pb PWM_block_design_wrapper_utilization_synth.pb }
