# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/shubhang/eldlabs/DSP48/DSP48.cache/wt [current_project]
set_property parent.project_path /home/shubhang/eldlabs/DSP48/DSP48.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet /home/shubhang/eldlabs/DSP48/DSP48.runs/xbip_dsp48_macro_0_synth_1/xbip_dsp48_macro_0.dcp
set_property used_in_implementation false [get_files /home/shubhang/eldlabs/DSP48/DSP48.runs/xbip_dsp48_macro_0_synth_1/xbip_dsp48_macro_0.dcp]
add_files -quiet /home/shubhang/eldlabs/DSP48/DSP48.runs/xbip_dsp48_macro_1_synth_1/xbip_dsp48_macro_1.dcp
set_property used_in_implementation false [get_files /home/shubhang/eldlabs/DSP48/DSP48.runs/xbip_dsp48_macro_1_synth_1/xbip_dsp48_macro_1.dcp]
read_verilog -library xil_defaultlib {
  /home/shubhang/eldlabs/DSP48/DSP48.srcs/sources_1/imports/new/sseg.v
  /home/shubhang/eldlabs/DSP48/DSP48.srcs/sources_1/new/frequency_divider.v
  /home/shubhang/eldlabs/DSP48/DSP48.srcs/sources_1/imports/new/decoder.v
  /home/shubhang/eldlabs/DSP48/DSP48.srcs/sources_1/imports/eldlabs/lab6_deadline/lab6_deadline.srcs/sources_1/imports/sources_1/imports/new/debouncer.v
  /home/shubhang/eldlabs/DSP48/DSP48.srcs/sources_1/imports/new/clock_pulse.v
  /home/shubhang/eldlabs/DSP48/DSP48.srcs/sources_1/imports/eldlabs/lab5/lab5.srcs/sources_1/new/binarytobcd.v
  /home/shubhang/eldlabs/DSP48/DSP48.srcs/sources_1/new/top.v
}
read_xdc /home/shubhang/eldlabs/DSP48/DSP48.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /home/shubhang/eldlabs/DSP48/DSP48.srcs/constrs_1/new/constraints.xdc]

synth_design -top top -part xc7a35tcpg236-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
