set_property PACKAGE_PIN W5 [get_ports {clock}]
set_property IOSTANDARD LVCMOS33 [get_ports {clock}]

set_property PACKAGE_PIN U18 [get_ports {go}]
set_property IOSTANDARD LVCMOS33 [get_ports {go}]

set_property PACKAGE_PIN T18 [get_ports {clear}]
set_property IOSTANDARD LVCMOS33 [get_ports {clear}]

set_property PACKAGE_PIN R2 [get_ports {xin[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {xin[5]}]
set_property PACKAGE_PIN T1 [get_ports {xin[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {xin[4]}]
set_property PACKAGE_PIN U1 [get_ports {xin[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {xin[3]}]
set_property PACKAGE_PIN W2 [get_ports {xin[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {xin[2]}]
set_property PACKAGE_PIN R3 [get_ports {xin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {xin[1]}]
set_property PACKAGE_PIN T2 [get_ports {xin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {xin[0]}]

set_property PACKAGE_PIN T3 [get_ports {yin[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {yin[5]}]
set_property PACKAGE_PIN V2 [get_ports {yin[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {yin[4]}]
set_property PACKAGE_PIN W13 [get_ports {yin[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {yin[3]}]
set_property PACKAGE_PIN W14 [get_ports {yin[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {yin[2]}]
set_property PACKAGE_PIN V15 [get_ports {yin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {yin[1]}]
set_property PACKAGE_PIN W15 [get_ports {yin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {yin[0]}]

set_property PACKAGE_PIN W4 [get_ports {boardanode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardanode[3]}]
set_property PACKAGE_PIN V4 [get_ports {boardanode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardanode[2]}]
set_property PACKAGE_PIN U4 [get_ports {boardanode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardanode[1]}]
set_property PACKAGE_PIN U2 [get_ports {boardanode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardanode[0]}]

set_property PACKAGE_PIN W7 [get_ports {boardcathode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardcathode[7]}]
set_property PACKAGE_PIN W6 [get_ports {boardcathode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardcathode[6]}]
set_property PACKAGE_PIN U8 [get_ports {boardcathode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardcathode[5]}]
set_property PACKAGE_PIN V8 [get_ports {boardcathode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardcathode[4]}]
set_property PACKAGE_PIN U5 [get_ports {boardcathode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardcathode[3]}]
set_property PACKAGE_PIN V5 [get_ports {boardcathode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardcathode[2]}]
set_property PACKAGE_PIN U7 [get_ports {boardcathode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardcathode[1]}]
set_property PACKAGE_PIN V7 [get_ports {boardcathode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {boardcathode[0]}]


set_property PACKAGE_PIN A14 [get_ports {pmodcathode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmodcathode[6]}]
set_property PACKAGE_PIN A16 [get_ports {pmodcathode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmodcathode[5]}]
set_property PACKAGE_PIN B15 [get_ports {pmodcathode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmodcathode[4]}]
set_property PACKAGE_PIN B16 [get_ports {pmodcathode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmodcathode[3]}]
set_property PACKAGE_PIN K17 [get_ports {pmodcathode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmodcathode[2]}]
set_property PACKAGE_PIN M18 [get_ports {pmodcathode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmodcathode[1]}]
set_property PACKAGE_PIN N17 [get_ports {pmodcathode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmodcathode[0]}]

set_property PACKAGE_PIN P18 [get_ports {pmodanode}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmodanode}]


set_property PACKAGE_PIN U19 [get_ports {state[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[2]}]
set_property PACKAGE_PIN E19 [get_ports {state[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[1]}]
set_property PACKAGE_PIN U16 [get_ports {state[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[0]}]


set_property PACKAGE_PIN N3 [get_ports {gcd[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gcd[5]}]
set_property PACKAGE_PIN P3 [get_ports {gcd[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gcd[4]}]
set_property PACKAGE_PIN U3 [get_ports {gcd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gcd[3]}]
set_property PACKAGE_PIN W3 [get_ports {gcd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gcd[2]}]
set_property PACKAGE_PIN V3 [get_ports {gcd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gcd[1]}]
set_property PACKAGE_PIN V13 [get_ports {gcd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gcd[0]}]
